### ISSUE TITLE
CryptographicException with unpatched libg.so

### ISSUE THREAD

**Issue by devinvisible** [clugh/coc-proxy-csharp#1]
```
System.Security.Cryptography.CryptographicException occurred
  HResult=-2146233296
  Message=Failed to open PublicKeyBox
  Source=Sodium
  StackTrace:
       at Sodium.PublicKeyBox.Open(Byte[] cipherText, Byte[] nonce, Byte[] secretKey, Byte[] publicKey)
       at coc_proxy_csharp.ServerCrypto.DecryptPacket(Socket socket, ServerState state, Byte[] packet) in coc-proxy-csharp\ServerCrypto.cs:line 36
  InnerException: 
```

This is almost certainly due to running without a patched libg.so. I can see there are hardcoded keys for both the client and server at the top of ClientCrypto and ServerCrypto. My guess is that I need to update this with the appropriate data for my real client (on ios). Are those keys listed anywhere currently?

**Comment by clugh** [comment]
Patching `libg.so` is required, which is why it is listed in the installation procedure in the [readme](https://github.com/clugh/coc-proxy-csharp/blob/master/README.md).  The public key is `72f1a4a4c48e44da0c42310f800e96624e6dc6a641a9d41c3b5039d8dfadc27e`.

**Comment by devinvisible** [comment]
Ah, didn't realize this proxy relied on that. I thought it was a generic proxy for the latest client. I'm not using an android phone - an iphone instead. Not sure if it has the same client keys as android has.

**Comment by clugh** [comment]
To be able to decrypt the packets, you must know the secret key for either the client or server.  Since Supercell isn't sharing the one for the server, and the one for the client is dynamically generated for every connection, we're forced to patch the client (or read the client's secret key from memory, for example with Frida).

**Comment by clugh** [comment]
And from expl0itr's [post](https://github.com/FICTURE7/CoCSharp/issues/54#issuecomment-175131078) in the CoCSharp thread, it appears the key is the same for iOS, but at offset `.data:004F37D8`.

**Warning:**  The `.data` offset (`.data:006023F8`) does not line up with the `dd` offset (`6296568`) for me in the android/x86 version of the file, so be careful when using the above.

**Comment by devinvisible** [comment]
I think the terminology is tripping me up. The server and client both have a public key and private key each. I thought the server's private key + client's private key was called a shared secret key. I thought it would be identical to the server's public key and the client's private key.

The 24 bytes sent in 20100 are not a true server public key (as its changes every time) but acts like one. It allows the client to come up with a secret key based on the client private key embedded in libg.so. I'd like to code the client latest private key in my proxy and require the client to always be running the latest version (this won't be a public proxy). That seems like it would work and avoid the need to patch libg.so, right?  Maybe I'm still misunderstanding something... :(

**Comment by clugh** [comment]
The 24 byte binary string in 20100 has no impact on the encryption.  With every release, Supercell generates a key pair.  They keep the private key secret and put the public key in the client.  Every time the client connects to the server, it generates another key pair then sends the public key to the server (in packet 10101).

Since the server has the original private key and now the client's public key (from packet 10101), it can generate a shared key.

Since the client has it's newly generated secret key and the server's public key (embedded in the client), it can generate the same shared key.

**Comment by devinvisible** [comment]
I better understand now - thank you for your patience. I was really hoping there would be a way to use a proxy with my non-jailbroken iphone. Because the server's public key is embedded in libg.so, it looks like it won't be possible to spoof the server (without, of course, the accompanying private key).
